import fs from "node:fs/promises";
import path from "node:path";
import { atomicWriteJson } from "./atomic-files.mjs";
export const INSTINCT_DOMAINS = ["code-style", "testing", "git", "debugging", "workflow", "security", "architecture", "tooling", "performance", "documentation", "general"];
export const INSTINCT_SCOPES = ["project", "global"];
export const INSTINCT_SOURCES = ["agent", "observation", "task-outcome", "import", "hook"];
const normalize = (v) => String(v ?? "").replace(/\s+/g, " ").trim(), round = (v) => Number(Number(v).toFixed(3)), clamp = (v) => Math.max(.1, Math.min(.95, Number(v) || 0));
const tokens = (v) => new Set(String(v ?? "").toLowerCase().split(/[^a-z0-9а-яё]+/i).filter((x) => x.length >= 3));
export function instinctId(trigger, action) { return `${normalize(trigger)} ${normalize(action)}`.toLowerCase().replace(/^when\s+/, "").replace(/[^a-z0-9а-яё]+/gi, "-").replace(/^-+|-+$/g, "").split("-").filter(Boolean).slice(0, 8).join("-") || "instinct"; }
export function initialConfidence(count) { count = Math.max(1, Number(count) || 1); return count >= 11 ? .85 : count >= 6 ? .7 : count >= 3 ? .5 : .3; }
export function effectiveConfidence(item, now = new Date().toISOString()) { const last = Date.parse(item.last_observed_at || item.updated_at || item.created_at || now), weeks = Number.isFinite(last) ? Math.max(0, (Date.parse(now) - last) / 604800000) : 0; return round(Math.max(Math.min(item.confidence, .3), item.confidence - Math.floor(weeks) * .02)); }
const similar = (a, b) => { const x = tokens(`${a.trigger} ${a.action}`), y = tokens(`${b.trigger} ${b.action}`); let shared = 0; for (const w of x) if (y.has(w)) shared++; return x.size && y.size && shared / Math.min(x.size, y.size) >= .75; };
export function renderInstinctsMarkdown(items) { return items?.length ? ["Active instincts:", ...items.map((x) => `- [${x.scope} ${Math.round(x.effective_confidence * 100)}%] ${x.action} (${x.trigger})`)].join("\n") : ""; }
export function renderInstinctSkillDraft(cluster, { projectName = "" } = {}) { const name = cluster.skill_name; const lines = cluster.instincts.map((x, i) => `${i + 1}. When ${x.trigger}: ${x.action} (confidence ${Math.round(x.effective_confidence * 100)}%)`); return { name, markdown: `---\nname: ${name}\ndescription: "Use when working on ${cluster.domain} tasks${projectName ? ` in the ${projectName} project` : ""}."\n---\n\n# ${name}\n\n## Workflow\n\n${lines.join("\n")}\n\n## Guardrails\n\n- Verify each learned behavior against the current task before applying it.\n` }; }
export class InstinctStore { constructor({ stateRoot }) { this.stateRoot = path.resolve(stateRoot); this.filePath = path.join(this.stateRoot, "instincts.json"); this.queue = Promise.resolve(); } async read() { try { const x = JSON.parse(await fs.readFile(this.filePath, "utf8")); return { schema_version: 1, updated_at: null, instincts: Array.isArray(x.instincts) ? x.instincts : [] }; } catch (e) { if (e?.code === "ENOENT") return { schema_version: 1, updated_at: null, instincts: [] }; throw e; } } async update(fn) { this.queue = this.queue.catch(() => undefined).then(async () => { const x = await this.read(), n = await fn(x) || x; n.schema_version = 1; n.updated_at = new Date().toISOString(); n.instincts = (n.instincts || []).slice(-5000); await atomicWriteJson(this.filePath, n); return n; }); return this.queue; }
  async record(input) { const trigger = normalize(input.trigger), action = normalize(input.action); if (!trigger || !action) throw new Error("trigger and action are required."); const domain = INSTINCT_DOMAINS.includes(input.domain) ? input.domain : "general", scope = INSTINCT_SCOPES.includes(input.scope) ? input.scope : "project"; if (scope === "project" && !input.projectId) throw new Error("projectId is required for project-scoped instincts."); const now = input.now || new Date().toISOString(); let result; await this.update((store) => { const id = instinctId(trigger, action), existing = store.instincts.find((x) => x.status !== "retired" && (x.id === id || similar(x, { trigger, action })) && (x.scope === "global" || scope === "global" || x.project_id === input.projectId)); if (existing) { const added = Math.max(1, Number(input.observations) || 1); existing.observations += added; existing.confidence = round(clamp(Math.max(existing.confidence + .05 * added, initialConfidence(existing.observations)))); existing.last_observed_at = existing.updated_at = now; existing.evidence = [...(existing.evidence || []).slice(-19), { at: now, kind: "observe", note: normalize(input.note), task_id: String(input.taskId || ""), source: input.source || "agent" }]; for (const s of input.stack ?? []) if (!existing.stack.includes(s)) existing.stack.push(s); result = { instinct: structuredClone(existing), created: false }; return store; } const observations = Math.max(1, Number(input.observations) || 1); const instinct = { id, trigger, action, domain, scope, project_id: scope === "project" ? String(input.projectId) : "", project_name: scope === "project" ? String(input.projectName || "") : "", confidence: round(clamp(input.confidence !== undefined ? input.confidence : initialConfidence(observations))), observations, source: INSTINCT_SOURCES.includes(input.source) ? input.source : "agent", stack: [...new Set((input.stack ?? []).map(String))], status: "active", created_at: now, updated_at: now, last_observed_at: now, evidence: [{ at: now, kind: "observe", note: normalize(input.note), task_id: String(input.taskId || ""), source: input.source || "agent" }], promoted_to: null }; store.instincts.push(instinct); result = { instinct: structuredClone(instinct), created: true }; return store; }); return result; }
  async adjust(id, kind, { note = "", taskId = "", now = new Date().toISOString() } = {}) { let updated; await this.update((store) => { const x = store.instincts.find((item) => item.id === id); if (!x) throw new Error(`Unknown instinct: ${id}`); if (kind === "confirm") { x.observations++; x.confidence = round(clamp(x.confidence + .05)); x.last_observed_at = now; if (x.status === "retired") x.status = "active"; } else if (kind === "contradict") { x.confidence = round(clamp(x.confidence - .1)); if (x.confidence < .2) x.status = "retired"; } else if (kind === "retire") x.status = "retired"; else if (kind === "promote") { if (x.scope === "global") throw new Error(`Instinct ${id} is already global.`); x.scope = "global"; x.project_id = x.project_name = ""; } else throw new Error(`Unknown adjustment: ${kind}`); x.updated_at = now; x.evidence = [...(x.evidence || []).slice(-19), { at: now, kind, note: normalize(note), task_id: String(taskId), source: "agent" }]; updated = structuredClone(x); return store; }); return updated; }
  async list({ projectId = "", scope = "", domain = "", minConfidence = 0, includeRetired = false, now = new Date().toISOString() } = {}) { return (await this.read()).instincts.filter((x) => includeRetired || x.status === "active").filter((x) => !projectId || x.scope === "global" || x.project_id === projectId).filter((x) => !scope || x.scope === scope).filter((x) => !domain || x.domain === domain).map((x) => ({ ...x, effective_confidence: effectiveConfidence(x, now) })).filter((x) => x.effective_confidence >= minConfidence).sort((a, b) => b.effective_confidence - a.effective_confidence || a.id.localeCompare(b.id)); }
  async rankForContext({ projectId = "", stack = [], task = "", threshold = .7, limit = 6, now = new Date().toISOString() } = {}) { const candidates = await this.list({ projectId, minConfidence: threshold, now }), stackTokens = new Set(stack.flatMap((x) => [...tokens(x)])), taskTokens = tokens(task); const instincts = candidates.map((x) => { let boost = x.scope === "project" ? .25 : 0; if ([...tokens(`${x.domain} ${x.trigger} ${x.stack.join(" ")}`)].some((w) => stackTokens.has(w))) boost += .2; if ([...tokens(`${x.trigger} ${x.action}`)].some((w) => taskTokens.has(w))) boost += .15; return { ...x, relevance: round(x.effective_confidence + boost) }; }).sort((a, b) => b.relevance - a.relevance || a.id.localeCompare(b.id)).slice(0, Math.max(1, Math.min(Number(limit) || 6, 20))); return { instincts, markdown: renderInstinctsMarkdown(instincts) }; }
  async promotionCandidates() { const groups = new Map(); for (const x of (await this.read()).instincts) if (x.status !== "retired" && x.scope === "project") groups.set(x.id, [...(groups.get(x.id) || []), x]); return [...groups].map(([id, xs]) => ({ id, projects: new Set(xs.map((x) => x.project_id)).size, average_confidence: round(xs.reduce((n, x) => n + x.confidence, 0) / xs.length), domain: xs[0].domain, trigger: xs[0].trigger, action: xs[0].action })).filter((x) => x.projects >= 2 && x.average_confidence >= .8); }
  async clusters({ projectId = "", minSize = 3 } = {}) { const groups = new Map(); for (const x of await this.list({ projectId })) { const key = `${x.scope}:${x.domain}`; groups.set(key, [...(groups.get(key) || []), x]); } return [...groups].filter(([, xs]) => xs.length >= Math.max(2, Number(minSize) || 3)).map(([key, instincts]) => ({ key, domain: instincts[0].domain, scope: instincts[0].scope, instincts, skill_name: `learned-${instincts[0].domain}${instincts[0].scope === "project" ? `-${String(instincts[0].project_name || instincts[0].project_id).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 24) || "project"}` : ""}` })); }
  async markPromoted(ids, target) { await this.update((store) => { for (const x of store.instincts) if (ids.includes(x.id)) { x.status = "promoted"; x.promoted_to = target; } return store; }); }
  async exportInstincts({ projectId = "", scope = "", domain = "", minConfidence = .5, now } = {}) { const instincts = await this.list({ projectId, scope, domain, minConfidence, now }); return { schema_version: 1, instincts: instincts.map(({ evidence, created_at, updated_at, last_observed_at, effective_confidence, ...x }) => x) }; }
  async importInstincts(entries, { scope = "", projectId = "", projectName = "" } = {}) { const results = []; for (const entry of entries ?? []) results.push(await this.record({ ...entry, scope: scope || entry.scope || "project", projectId, projectName, source: "import", confidence: Math.min(.7, Number(entry.confidence) || .3) })); return results; }
}
