import fs from "node:fs/promises";
import path from "node:path";
import { atomicWriteFile } from "./atomic-files.mjs";
import { COMMON_RULES, RULE_PACKS, packsForStack } from "./rules-catalog.mjs";

export const RULES_RELATIVE_DIR = ".ai-dev/rules";
/**
 * Where each agent tool reads a repository's instructions.
 *
 * The content is the same for all of them — the rules this system installs and
 * the workflow it expects — so what differs is only the file and whether the
 * tool owns the whole file (`file`) or shares it with the repository's own
 * prose (`section`). Adding a tool is a row here, not a branch.
 *
 * A tool absent from this table is not unsupported: every one of them also
 * reads `AGENTS.md`, which is the de-facto shared file, and every MCP client
 * receives the protocol in the server's initialize instructions.
 */
export const INSTRUCTION_SURFACES = Object.freeze([
  Object.freeze({ target: "agents-md", path: "AGENTS.md", mode: "section", tools: "Codex, Zed, OpenCode, Jules, Aider" }),
  Object.freeze({ target: "gemini-md", path: "GEMINI.md", mode: "section", tools: "Gemini CLI, Antigravity" }),
  Object.freeze({ target: "copilot", path: ".github/copilot-instructions.md", mode: "section", tools: "GitHub Copilot" }),
  Object.freeze({ target: "windsurf", path: ".windsurf/rules/ai-dev.md", mode: "file", tools: "Windsurf" }),
  Object.freeze({ target: "cline", path: ".clinerules/ai-dev.md", mode: "file", tools: "Cline, Roo Code" })
]);

export const RULE_TARGETS = [
  "ai-dev",
  "claude",
  "claude-md",
  "cursor",
  ...INSTRUCTION_SURFACES.map((surface) => surface.target)
];
/**
 * Installed when the caller names no target. `claude-md` is opt-in: it is the
 * alternative to `claude`, not an addition to it — installing both loads the
 * same common rules twice, once from `.claude/rules` and once through the
 * CLAUDE.md import.
 */
export const DEFAULT_RULE_TARGETS = ["ai-dev", "claude", "cursor", "agents-md"];
const AGENTS_SECTION = "## Engineering Rules";
const CLAUDE_MD_FILE = "CLAUDE.md";
const GENERATED_MARKER = "<!-- generated by ai-dev-system install_project_rules; edit .ai-dev/rules instead -->";

function packById(id) {
  const pack = RULE_PACKS.find((item) => item.id === id);
  if (!pack) throw new Error(`Unknown rule pack: ${id}. Known packs: ${RULE_PACKS.map((item) => item.id).join(", ")}`);
  return pack;
}

function frontmatterList(values) {
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

/**
 * Render the canonical `.ai-dev/rules` documents: common rules without
 * frontmatter (always apply) and one file per pack with `paths:` globs.
 *
 * @param {string[]} packIds
 * @returns {Array<{ path: string, content: string, kind: "common" | "pack", id: string }>}
 */
export function renderCanonicalRules(packIds) {
  const files = COMMON_RULES.map((rule) => ({
    path: `${RULES_RELATIVE_DIR}/common/${rule.id}.md`,
    kind: "common",
    id: rule.id,
    content: `${rule.content.trimEnd()}\n`
  }));
  for (const id of packIds) {
    const pack = packById(id);
    files.push({
      path: `${RULES_RELATIVE_DIR}/${pack.id}.md`,
      kind: "pack",
      id: pack.id,
      content: `---\npaths: ${frontmatterList(pack.paths)}\n---\n\n${pack.content.trimEnd()}\n`
    });
  }
  return files;
}

/**
 * Claude Code projection: `.claude/rules/ai-dev/<name>.md` (common files
 * always apply; pack files keep their `paths:` frontmatter).
 *
 * @param {string[]} packIds
 * @returns {Array<{ path: string, content: string }>}
 */
export function renderClaudeRules(packIds) {
  return renderCanonicalRules(packIds).map((file) => ({
    path: `.claude/rules/ai-dev/${file.kind === "common" ? `common-${file.id}` : file.id}.md`,
    content: `${GENERATED_MARKER}\n${file.content}`.replace(/^(<!--[^\n]*-->\n)(---\n)/, "$2")
  })).map((file) => {
    // Frontmatter must stay first for pack files: move the marker below it.
    if (file.content.startsWith("---\n")) {
      const end = file.content.indexOf("\n---\n", 4) + 5;
      return { ...file, content: `${file.content.slice(0, end)}\n${GENERATED_MARKER}\n${file.content.slice(end)}` };
    }
    return file;
  });
}

/**
 * Cursor projection: `.cursor/rules/ai-dev-<name>.mdc` with
 * `description` / `globs` / `alwaysApply` frontmatter.
 *
 * @param {string[]} packIds
 * @returns {Array<{ path: string, content: string }>}
 */
export function renderCursorRules(packIds) {
  const files = COMMON_RULES.map((rule) => ({
    path: `.cursor/rules/ai-dev-common-${rule.id}.mdc`,
    content: `---\ndescription: ${JSON.stringify(`AI Dev System common rule: ${rule.title}`)}\nalwaysApply: true\n---\n\n${rule.content.trimEnd()}\n`
  }));
  for (const id of packIds) {
    const pack = packById(id);
    files.push({
      path: `.cursor/rules/ai-dev-${pack.id}.mdc`,
      content: `---\ndescription: ${JSON.stringify(`AI Dev System rules: ${pack.title}`)}\nglobs: ${frontmatterList(pack.paths)}\nalwaysApply: false\n---\n\n${pack.content.trimEnd()}\n`
    });
  }
  return files;
}

/**
 * CLAUDE.md projection: instead of copying the rules into `.claude/rules`,
 * point Claude Code at the canonical files with `@path` imports, which it
 * expands into the session at startup.
 *
 * One import line per file: Claude Code resolves an import as a path, not as a
 * glob, so `@.ai-dev/rules/common/*.md` would import nothing. Only the
 * always-on common rules are imported; the packs are path-scoped, so they are
 * listed as plain paths inside backticks — which import parsing skips — to be
 * read when their files are touched. Use this target instead of `claude`, not
 * alongside it.
 *
 * @param {string[]} packIds
 * @returns {string}
 */
export function renderClaudeMdSection(packIds) {
  const lines = [
    AGENTS_SECTION,
    "",
    GENERATED_MARKER,
    "",
    `Always-on engineering rules, imported from \`${RULES_RELATIVE_DIR}\` (edit them there, not here):`,
    "",
    ...COMMON_RULES.map((rule) => `@${RULES_RELATIVE_DIR}/common/${rule.id}.md`),
    ""
  ];
  if (packIds.length) {
    lines.push(
      "Language packs are not imported: read the pack before changing the files it covers. They override common rules on conflict.",
      "",
      ...packIds.map((id) => {
        const pack = packById(id);
        return `- ${pack.title}: \`${RULES_RELATIVE_DIR}/${pack.id}.md\` (${pack.paths.slice(0, 3).join(", ")}${pack.paths.length > 3 ? ", ..." : ""})`;
      }),
      ""
    );
  }
  lines.push("Non-negotiables: no secrets in code, no `--no-verify`, no skipped or deleted tests to hide failures, no unrelated refactors, verify with `verify_task` before `complete_task`.");
  return lines.join("\n");
}

/**
 * The `## Engineering Rules` section for AGENTS.md: a short index pointing at
 * the canonical files so clients without path-scoped rules still see them.
 *
 * @param {string[]} packIds
 * @returns {string}
 */
export function renderAgentsRulesSection(packIds) {
  const lines = [
    AGENTS_SECTION,
    "",
    "Work in this repository runs through the ai-dev-system MCP server. Two protocols apply to every substantive task, whichever assistant is reading this:",
    "",
    "1. **Intent gate (`grill-me`)** — before touching anything, restate the request, separate what is known from what is assumed, ask only the questions whose answers change the work, and state what done means. It is supplemental: it does not take one of the three routed skill slots.",
    "2. **Task lifecycle (`ai-dev-orchestrator`)** — `begin_task` (or `begin_task_in_worktree`) to open the task and compile its context, at most the three skills it routes, `checkpoint_task` for progress and decisions, `verify_task` for evidence, `complete_task` only when every criterion is met or waived with a reason.",
    "",
    "Read either protocol in full with `read_skill`. If the MCP server is unavailable, follow the rules below and say in the final answer that the lifecycle tools could not be used.",
    "",
    "Always-on engineering rules live in `.ai-dev/rules/`. Read them before changing code; language packs apply to matching files and override common rules on conflict.",
    "",
    ...COMMON_RULES.map((rule) => `- Common: \`${RULES_RELATIVE_DIR}/common/${rule.id}.md\` (${rule.title})`),
    ...packIds.map((id) => {
      const pack = packById(id);
      return `- ${pack.title}: \`${RULES_RELATIVE_DIR}/${pack.id}.md\` (${pack.paths.slice(0, 3).join(", ")}${pack.paths.length > 3 ? ", ..." : ""})`;
    }),
    "",
    "Non-negotiables: no secrets in code, no `--no-verify`, no skipped or deleted tests to hide failures, no unrelated refactors, verify with `verify_task` before `complete_task`."
  ];
  return lines.join("\n");
}

/**
 * Replace (or append) one `## Section` in a Markdown document.
 *
 * @param {string} text - Existing document (may be empty).
 * @param {string} heading - Exact `## Heading` line.
 * @param {string} section - Full replacement section starting with the heading.
 * @returns {string}
 */
export function replaceMarkdownSection(text, heading, section) {
  const source = String(text ?? "").replace(/\r\n/g, "\n");
  const lines = source.split("\n");
  const start = lines.findIndex((line) => line.trim() === heading);
  if (start === -1) {
    const base = source.trimEnd();
    return `${base ? `${base}\n\n` : ""}${section.trimEnd()}\n`;
  }
  let end = lines.length;
  for (let index = start + 1; index < lines.length; index += 1) {
    if (/^## /.test(lines[index])) {
      end = index;
      break;
    }
  }
  const before = lines.slice(0, start).join("\n").trimEnd();
  const after = lines.slice(end).join("\n").trimStart();
  return `${before ? `${before}\n\n` : ""}${section.trimEnd()}\n${after ? `\n${after}` : ""}`;
}

/**
 * Plan every file an installation would write. A `section` entry is merged into
 * the `heading` section of an existing Markdown document instead of replacing
 * the file.
 *
 * @param {{ packIds: string[], targets?: string[] }} input
 * @returns {Array<{ target: string, path: string, content?: string, section?: string, heading?: string }>}
 */
export function planRuleFiles({ packIds, targets = DEFAULT_RULE_TARGETS }) {
  const files = [];
  const wanted = new Set(targets);
  for (const target of wanted) {
    if (!RULE_TARGETS.includes(target)) throw new Error(`Unknown rules target: ${target}. Known: ${RULE_TARGETS.join(", ")}`);
  }
  if (wanted.has("ai-dev")) files.push(...renderCanonicalRules(packIds).map((file) => ({ target: "ai-dev", path: file.path, content: file.content })));
  if (wanted.has("claude")) files.push(...renderClaudeRules(packIds).map((file) => ({ target: "claude", ...file })));
  if (wanted.has("claude-md")) files.push({ target: "claude-md", path: CLAUDE_MD_FILE, heading: AGENTS_SECTION, section: renderClaudeMdSection(packIds) });
  if (wanted.has("cursor")) files.push(...renderCursorRules(packIds).map((file) => ({ target: "cursor", ...file })));
  for (const surface of INSTRUCTION_SURFACES) {
    if (!wanted.has(surface.target)) continue;
    const section = renderAgentsRulesSection(packIds);
    files.push(surface.mode === "section"
      ? { target: surface.target, path: surface.path, heading: AGENTS_SECTION, section }
      : { target: surface.target, path: surface.path, content: `${GENERATED_MARKER}\n\n${section}\n` });
  }
  return files;
}

/**
 * The instruction files worth writing for this repository, on top of the
 * defaults: the ones whose tool has left a trace here or on this machine.
 *
 * Writing every file into every repository is clutter, and writing only
 * `AGENTS.md` leaves Copilot, Gemini, Windsurf and Cline reading nothing. So
 * the answer is what the repository shows: a `.github/` directory means
 * Copilot's file has a home, a `.windsurf/` directory means Windsurf is in use,
 * and a `~/.gemini` means the Gemini CLI is installed for this person.
 *
 * @param {object} input
 * @param {string} input.projectRoot
 * @param {string} [input.homeDir]
 * @param {(target: string) => boolean} input.exists - Injected; `fs.existsSync` in production.
 * @returns {string[]} Targets from {@link INSTRUCTION_SURFACES}, defaults included.
 */
export function detectInstructionTargets({ projectRoot, homeDir = "", exists }) {
  const inProject = (...parts) => exists(path.join(projectRoot, ...parts));
  const inHome = (...parts) => Boolean(homeDir) && exists(path.join(homeDir, ...parts));
  const found = new Set(DEFAULT_RULE_TARGETS);
  if (inProject(".github") || inProject(".github", "copilot-instructions.md")) found.add("copilot");
  if (inProject("GEMINI.md") || inHome(".gemini")) found.add("gemini-md");
  if (inProject(".windsurf") || inProject(".windsurfrules") || inHome(".codeium")) found.add("windsurf");
  if (inProject(".clinerules") || inHome(".cline")) found.add("cline");
  return RULE_TARGETS.filter((target) => found.has(target));
}

async function readIfExists(target) {
  try {
    return await fs.readFile(target, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

/**
 * Install the rules into a repository. Existing files are left alone unless
 * `overwrite` is set (generated Claude/Cursor projections are always refreshed
 * because they carry the generated marker). AGENTS.md and, for the `claude-md`
 * target, CLAUDE.md get their `## Engineering Rules` section replaced in place.
 *
 * @param {{ projectRoot: string, stack?: string[], projectTypes?: string[], packs?: string[], targets?: string[], overwrite?: boolean, dryRun?: boolean }} input
 * @returns {Promise<{ packs: string[], targets: string[], written: string[], updated: string[], skipped: string[], planned: string[] }>}
 */
export async function installProjectRules({ projectRoot, stack = [], projectTypes = [], packs, targets = DEFAULT_RULE_TARGETS, overwrite = false, dryRun = false }) {
  const root = path.resolve(projectRoot);
  const packIds = packs?.length ? packs.map((id) => packById(id).id) : packsForStack(stack, projectTypes);
  const plan = planRuleFiles({ packIds, targets });
  const written = [];
  const updated = [];
  const skipped = [];
  const planned = [];
  for (const file of plan) {
    const absolute = path.join(root, ...file.path.split("/"));
    if (file.section) {
      const current = (await readIfExists(absolute)) ?? "";
      const next = replaceMarkdownSection(current, file.heading || AGENTS_SECTION, file.section);
      if (next === current) {
        skipped.push(`${file.path} (section current)`);
        continue;
      }
      if (dryRun) {
        planned.push(file.path);
        continue;
      }
      await atomicWriteFile(absolute, next, "utf8");
      (current ? updated : written).push(file.path);
      continue;
    }
    const current = await readIfExists(absolute);
    if (current === file.content) {
      skipped.push(`${file.path} (current)`);
      continue;
    }
    const generated = current?.includes(GENERATED_MARKER);
    if (current !== null && !overwrite && !generated) {
      skipped.push(`${file.path} (exists; pass overwrite=true)`);
      continue;
    }
    if (dryRun) {
      planned.push(file.path);
      continue;
    }
    await atomicWriteFile(absolute, file.content, "utf8");
    (current === null ? written : updated).push(file.path);
  }
  return { packs: packIds, targets: [...new Set(targets)], written, updated, skipped, planned };
}

/**
 * Catalog listing for `list_rule_packs`.
 *
 * @returns {{ common: object[], packs: object[] }}
 */
export function describeRuleCatalog() {
  return {
    common: COMMON_RULES.map((rule) => ({ id: rule.id, title: rule.title, lines: rule.content.split("\n").length })),
    packs: RULE_PACKS.map((pack) => ({ id: pack.id, title: pack.title, paths: pack.paths, stacks: pack.stacks, lines: pack.content.split("\n").length }))
  };
}
