import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { COMMON_RULES, RULE_PACKS, packsForStack } from "./rules-catalog.mjs";
import {
  describeRuleCatalog,
  installProjectRules,
  planRuleFiles,
  renderAgentsRulesSection,
  renderClaudeRules,
  renderCursorRules,
  replaceMarkdownSection
} from "./rules-library.mjs";

test("catalog is well formed and stack mapping is additive", () => {
  assert.ok(COMMON_RULES.length >= 5);
  for (const rule of COMMON_RULES) assert.match(rule.content, /^# /);
  for (const pack of RULE_PACKS) {
    assert.ok(pack.paths.length > 0, pack.id);
    assert.ok(pack.stacks.length > 0, pack.id);
    assert.doesNotMatch(pack.content, /\b(TODO|TBD|FIXME)\b/);
  }
  assert.deepEqual(packsForStack(["Node.js", "TypeScript", "Next.js", "React", "Tailwind CSS", "Docker"]), ["typescript", "react", "web", "docker"]);
  assert.deepEqual(packsForStack(["Node.js"]), ["typescript"]);
  assert.deepEqual(packsForStack(["Python", "FastAPI"]), ["python"]);
  assert.deepEqual(packsForStack(["Vue"], ["frontend"]), ["web"]);
  assert.deepEqual(packsForStack([], ["frontend"]), ["web"]);
  assert.deepEqual(packsForStack(["Go", "Rust", "Java/JVM"]), ["golang", "rust", "java"]);
  const catalog = describeRuleCatalog();
  assert.equal(catalog.packs.length, RULE_PACKS.length);
});

test("projections carry the right frontmatter for Claude Code and Cursor", () => {
  const claude = renderClaudeRules(["typescript"]);
  const common = claude.find((file) => file.path.endsWith("common-coding-style.md"));
  assert.match(common.content, /^<!-- generated by ai-dev-system/);
  const pack = claude.find((file) => file.path.endsWith("/typescript.md"));
  assert.match(pack.content, /^---\npaths: \["\*\*\/\*\.ts"/);
  assert.match(pack.content, /\n---\n\n<!-- generated by ai-dev-system/);
  const cursor = renderCursorRules(["python"]);
  assert.match(cursor.find((file) => file.path.endsWith("ai-dev-python.mdc")).content, /globs: \["\*\*\/\*\.py", "\*\*\/\*\.pyi"\]\nalwaysApply: false/);
  assert.match(cursor.find((file) => file.path.endsWith("ai-dev-common-security.mdc")).content, /alwaysApply: true/);
  const section = renderAgentsRulesSection(["typescript", "web"]);
  assert.match(section, /^## Engineering Rules/);
  assert.match(section, /TypeScript \/ JavaScript: `\.ai-dev\/rules\/typescript\.md`/);
  assert.throws(() => planRuleFiles({ packIds: ["cobol"] }), /Unknown rule pack: cobol/);
  assert.throws(() => planRuleFiles({ packIds: [], targets: ["vim"] }), /Unknown rules target: vim/);
});

test("replaceMarkdownSection replaces in place or appends", () => {
  const original = "# AGENTS.md\n\n## Project\n\n- Name: x\n\n## Engineering Rules\n\nold\n\n## Skill Routing\n\n- feature\n";
  const next = replaceMarkdownSection(original, "## Engineering Rules", "## Engineering Rules\n\nnew body");
  assert.equal(next, "# AGENTS.md\n\n## Project\n\n- Name: x\n\n## Engineering Rules\n\nnew body\n\n## Skill Routing\n\n- feature\n");
  assert.equal(replaceMarkdownSection("", "## Engineering Rules", "## Engineering Rules\n\nbody"), "## Engineering Rules\n\nbody\n");
  assert.equal(replaceMarkdownSection("# A\n", "## Engineering Rules", "## Engineering Rules\n\nbody"), "# A\n\n## Engineering Rules\n\nbody\n");
});

test("installProjectRules writes canonical files and projections, respects existing files, and is idempotent", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "rules-library-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.writeFile(path.join(root, "AGENTS.md"), "# AGENTS.md\n\n## Project\n\n- Name: fixture\n");

  const dry = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript", "React"], dryRun: true });
  assert.deepEqual(dry.packs, ["typescript", "react", "web"]);
  assert.ok(dry.planned.includes(".ai-dev/rules/common/coding-style.md"));
  assert.ok(dry.planned.includes("AGENTS.md"));
  assert.equal(await fs.access(path.join(root, ".ai-dev")).then(() => true).catch(() => false), false);

  const first = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript", "React"] });
  assert.ok(first.written.includes(".ai-dev/rules/typescript.md"));
  assert.ok(first.written.includes(".claude/rules/ai-dev/common-testing.md"));
  assert.ok(first.written.includes(".cursor/rules/ai-dev-react.mdc"));
  assert.ok(first.updated.includes("AGENTS.md"));
  const agents = await fs.readFile(path.join(root, "AGENTS.md"), "utf8");
  assert.match(agents, /## Engineering Rules/);
  assert.match(agents, /- Name: fixture/);

  const second = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript", "React"] });
  assert.equal(second.written.length, 0);
  assert.equal(second.updated.length, 0);
  assert.ok(second.skipped.length > 0);

  await fs.writeFile(path.join(root, ".ai-dev", "rules", "typescript.md"), "# my custom typescript rules\n");
  const third = await installProjectRules({ projectRoot: root, packs: ["typescript"], targets: ["ai-dev"] });
  assert.ok(third.skipped.some((item) => item.startsWith(".ai-dev/rules/typescript.md (exists")));
  assert.equal(await fs.readFile(path.join(root, ".ai-dev", "rules", "typescript.md"), "utf8"), "# my custom typescript rules\n");
  const forced = await installProjectRules({ projectRoot: root, packs: ["typescript"], targets: ["ai-dev"], overwrite: true });
  assert.ok(forced.updated.includes(".ai-dev/rules/typescript.md"));
});
