import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { LOCKFILE_MANAGERS, LOCKFILE_SEARCH_DEPTH, markerDirectories, readLockfileFacts, yarnAuditArgs } from "./security-scan-lockfiles.mjs";

async function tree(t, files) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "lockfiles-"));
  t.after(() => fs.rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }));
  for (const [name, content] of Object.entries(files)) {
    await fs.mkdir(path.dirname(path.join(root, name)), { recursive: true });
    await fs.writeFile(path.join(root, name), content, "utf8");
  }
  return root;
}

const relative = (root, directories) => directories.map((item) => path.relative(root, item).split(path.sep).join("/") || ".");

test("a frontend and a backend with no lockfile at the root are both found", async (t) => {
  const root = await tree(t, {
    "frontend/package-lock.json": "{}",
    "backend/package-lock.json": "{}",
    "README.md": "# app"
  });
  assert.deepEqual(relative(root, await markerDirectories(root, ["package-lock.json"])), ["backend", "frontend"]);
});

test("the search stops two levels down and skips what is not a project's own tree", async (t) => {
  assert.equal(LOCKFILE_SEARCH_DEPTH, 2);
  const root = await tree(t, {
    "package-lock.json": "{}",
    "apps/web/package-lock.json": "{}",
    "apps/web/deep/er/package-lock.json": "{}",
    "node_modules/left-pad/package-lock.json": "{}",
    "test/fixtures/package-lock.json": "{}",
    "dist/package-lock.json": "{}",
    ".cache/package-lock.json": "{}",
    "packages/lib/pnpm-lock.yaml": "lockfileVersion: 9"
  });
  assert.deepEqual(relative(root, await markerDirectories(root, ["package-lock.json"])), [".", "apps/web"]);
  assert.deepEqual(relative(root, await markerDirectories(root, ["pnpm-lock.yaml"])), ["packages/lib"]);
  assert.deepEqual(await markerDirectories(root, ["Cargo.lock"]), []);
  assert.deepEqual(await markerDirectories(path.join(root, "missing"), ["package-lock.json"]), [], "an unreadable root is no directories, not a throw");
});

test("a symbolic link to a directory is not followed", async (t) => {
  const root = await tree(t, { "real/package-lock.json": "{}" });
  try {
    await fs.symlink(path.join(root, "real"), path.join(root, "linked"), "dir");
  } catch {
    t.skip("this host cannot create directory symlinks");
    return;
  }
  assert.deepEqual(relative(root, await markerDirectories(root, ["package-lock.json"])), ["real"]);
});

test("Yarn 2+ is told apart from Yarn 1 by packageManager, then by .yarnrc.yml", async (t) => {
  const berry = ["npm", "audit", "--all", "--recursive", "--json"];
  const classic = ["audit", "--json"];
  assert.deepEqual(await yarnAuditArgs(await tree(t, { "package.json": JSON.stringify({ packageManager: "yarn@4.10.3" }) })), berry);
  assert.deepEqual(await yarnAuditArgs(await tree(t, { "package.json": JSON.stringify({ packageManager: "yarn@1.22.22" }), ".yarnrc.yml": "" })), classic, "the declaration wins over the file");
  assert.deepEqual(await yarnAuditArgs(await tree(t, { "package.json": "{}", ".yarnrc.yml": "nodeLinker: node-modules\n" })), berry);
  assert.deepEqual(await yarnAuditArgs(await tree(t, { "package.json": "{}" })), classic);
  assert.deepEqual(await yarnAuditArgs(await tree(t, { "package.json": "{ not json" })), classic);
});

// Each lockfile below is the real format, as npm 10, pnpm 10, Yarn 1, Yarn 4
// and Bun 1.3 wrote it on 2026-09-27, cut down to a few packages.
const LOCKFILES = {
  "package-lock.json": JSON.stringify({
    lockfileVersion: 3,
    packages: {
      "": { name: "app", dependencies: { ajv: "8.17.1" } },
      "node_modules/ajv": { version: "8.17.1", dependencies: { "fast-uri": "^3.0.1" } },
      "node_modules/fast-uri": { version: "3.1.8" },
      "node_modules/other/node_modules/fast-uri": { version: "2.4.0" },
      "node_modules/@scope/pkg": { version: "1.0.0", optionalDependencies: { "fast-uri": "^2.0.0" } },
      "packages/local": { version: "0.0.0" },
      "node_modules/local": { resolved: "packages/local", link: true }
    }
  }),
  "pnpm-lock.yaml": "lockfileVersion: '9.0'\n\nimporters:\n\n  .:\n    dependencies:\n      ajv:\n        specifier: 8.17.1\n        version: 8.17.1\n\npackages:\n\n  '@scope/pkg@1.0.0':\n    resolution: {integrity: sha512-a}\n\n  ajv@8.17.1:\n    resolution: {integrity: sha512-b}\n\n  fast-uri@3.1.8:\n    resolution: {integrity: sha512-c}\n\n  react-dom@18.3.1(react@18.3.1):\n    resolution: {integrity: sha512-d}\n\nsnapshots:\n\n  ajv@8.17.1:\n    dependencies:\n      fast-uri: 3.1.8\n",
  "yarn-classic/yarn.lock": "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\najv@8.17.1:\n  version \"8.17.1\"\n  dependencies:\n    fast-uri \"^3.0.1\"\n\n\"@scope/pkg@^1.0.0\", \"@scope/pkg@^1.0.1\":\n  version \"1.0.2\"\n\nfast-uri@^3.0.1:\n  version \"3.1.8\"\n",
  "yarn-berry/yarn.lock": "__metadata:\n  version: 8\n  cacheKey: 10c0\n\n\"ajv@npm:8.17.1\":\n  version: 8.17.1\n  resolution: \"ajv@npm:8.17.1\"\n  dependencies:\n    fast-uri: \"npm:^3.0.1\"\n\n\"fast-uri@npm:^3.0.1\":\n  version: 3.1.8\n  resolution: \"fast-uri@npm:3.1.8\"\n",
  "bun.lock": "{\n  \"lockfileVersion\": 1,\n  \"workspaces\": {\n    \"\": {\n      \"name\": \"app\",\n      \"dependencies\": {\n        \"ajv\": \"8.17.1\",\n      },\n    },\n  },\n  \"packages\": {\n    \"ajv\": [\"ajv@8.17.1\", \"\", { \"dependencies\": { \"fast-uri\": \"^3.0.1\" } }, \"sha512-a\"],\n\n    \"fast-uri\": [\"fast-uri@3.1.8\", \"\", {}, \"sha512-b\"],\n\n    \"@scope/pkg\": [\"@scope/pkg@1.0.0\", \"\", {}, \"sha512-c\"],\n  }\n}\n"
};

test("every lockfile format says what is installed, and all but pnpm what dependents ask for", async (t) => {
  const root = await tree(t, LOCKFILES);
  const facts = async (name) => readLockfileFacts(path.join(root, name));
  const installed = (value, name) => [...(value.installed.get(name) ?? [])].sort();

  const npm = await facts("package-lock.json");
  assert.equal(npm.manager, "npm");
  assert.equal(npm.readable, true);
  assert.deepEqual(installed(npm, "fast-uri"), ["2.4.0", "3.1.8"], "nested copies count too");
  assert.deepEqual(installed(npm, "@scope/pkg"), ["1.0.0"]);
  assert.deepEqual(npm.requested.get("fast-uri"), ["^3.0.1", "^2.0.0"]);
  assert.equal(npm.installed.has("local"), false, "a workspace link is not an installed package");

  const pnpm = await facts("pnpm-lock.yaml");
  assert.deepEqual(installed(pnpm, "fast-uri"), ["3.1.8"]);
  assert.deepEqual(installed(pnpm, "@scope/pkg"), ["1.0.0"]);
  assert.deepEqual(installed(pnpm, "react-dom"), ["18.3.1"], "the peer suffix is not part of the version");
  assert.equal(pnpm.requested, null, "pnpm records what it resolved, not what was asked for");

  const classic = await facts("yarn-classic/yarn.lock");
  assert.deepEqual(installed(classic, "@scope/pkg"), ["1.0.2"]);
  assert.deepEqual(classic.requested.get("@scope/pkg"), ["^1.0.0", "^1.0.1"]);
  assert.deepEqual(classic.requested.get("fast-uri"), ["^3.0.1"]);

  const berry = await facts("yarn-berry/yarn.lock");
  assert.deepEqual(installed(berry, "fast-uri"), ["3.1.8"]);
  assert.deepEqual(berry.requested.get("fast-uri"), ["^3.0.1"], "the npm: protocol is not part of the range");
  assert.equal(berry.installed.has("__metadata"), false);

  const bun = await facts("bun.lock");
  assert.deepEqual(installed(bun, "fast-uri"), ["3.1.8"]);
  assert.deepEqual(installed(bun, "@scope/pkg"), ["1.0.0"]);
  assert.deepEqual(bun.requested.get("fast-uri"), ["^3.0.1"]);
  assert.deepEqual(bun.requested.get("ajv"), ["8.17.1"], "the workspace's own dependencies are requests too");
});

test("a lockfile that cannot be read says so instead of answering empty", async (t) => {
  const root = await tree(t, { "package-lock.json": "{ torn", "npm-shrinkwrap.json": JSON.stringify({ lockfileVersion: 1, dependencies: {} }), "bun.lockb": "binary" });
  for (const name of ["package-lock.json", "npm-shrinkwrap.json", "bun.lockb", "missing/yarn.lock", "Cargo.lock"]) {
    const facts = await readLockfileFacts(path.join(root, name));
    assert.equal(facts.readable, false, name);
    assert.equal(facts.installed.size, 0);
  }
  assert.equal(LOCKFILE_MANAGERS["bun.lockb"], "bun");
});
