import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { atomicWriteFile, atomicWriteJson } from "./atomic-files.mjs";

export const HANDOFF_RELATIVE_PATH = ".ai-dev/context/handoff.md";
export const FILE_STATUSES = ["complete", "in_progress", "broken", "not_started"];
const text = (value) => String(value ?? "").replace(/\r\n?/g, "\n").trim();
const list = (value) => (Array.isArray(value) ? value : value ? [value] : []).map(text).filter(Boolean);
const pairs = (value, first, second) => (Array.isArray(value) ? value : []).map((item) => typeof item === "string" ? { [first]: text(item), [second]: "" } : { [first]: text(item?.[first]), [second]: text(item?.[second]) }).filter((item) => item[first]);
const slug = (value) => text(value).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "session";
export function normalizeSessionRecord(input = {}) { const building = text(input.building), topic = text(input.topic); if (!topic && !building) throw new Error("topic or building is required."); return { topic: topic || building.split("\n")[0].slice(0, 120), building, worked: pairs(input.worked, "item", "evidence"), failed: pairs(input.failed, "approach", "reason"), untried: list(input.untried), files: (input.files ?? []).map((item) => { const filePath = text(typeof item === "string" ? item : item?.path); if (!filePath) return null; const status = text(item?.status).toLowerCase().replace(/[\s-]+/g, "_") || "in_progress"; return { path: filePath, status: FILE_STATUSES.includes(status) ? status : "in_progress", notes: text(item?.notes) }; }).filter(Boolean), decisions: pairs(input.decisions, "decision", "reason"), blockers: list(input.blockers), next_step: text(input.next_step), environment: text(input.environment) }; }
export function sessionSubstanceScore(record) { if (!record) return 0; const placeholder = /^\s*(\[.*\]|-|n\/a|none|tbd|todo)\s*$/i, meaningful = (value) => text(value).length >= 12 && !placeholder.test(value); return (meaningful(record.building) ? 2 : 0) + (meaningful(record.next_step) ? 3 : 0) + Math.min(3, (record.worked ?? []).filter((item) => meaningful(item.item)).length) + Math.min(3, (record.failed ?? []).filter((item) => meaningful(item.approach)).length) + Math.min(2, (record.files ?? []).length) + Math.min(2, (record.decisions ?? []).length + (record.blockers ?? []).length); }
export class SessionStore { constructor({ stateRoot }) { this.stateRoot = path.resolve(stateRoot); this.root = path.join(this.stateRoot, "sessions"); } directoryFor(projectId) { return path.join(this.root, String(projectId || "unknown").replace(/[^a-zA-Z0-9_.-]/g, "_")); } async save(input) { const record = normalizeSessionRecord(input), savedAt = input.now || new Date().toISOString(), id = `session-${savedAt.replace(/\D/g, "").slice(0, 14)}-${crypto.randomUUID().slice(0, 8)}`; const stored = { schema_version: 1, id, saved_at: savedAt, project_id: String(input.projectId || ""), project_path: String(input.projectPath || ""), project_name: String(input.projectName || path.basename(String(input.projectPath || "")) || ""), task_id: String(input.taskId || ""), branch: String(input.branch || ""), worktree: String(input.worktree || input.projectPath || ""), source: String(input.source || "agent"), client: String(input.client || ""), session_id: String(input.sessionId || ""), ...record }; const filePath = path.join(this.directoryFor(stored.project_id), `${savedAt.replace(/\D/g, "").slice(0, 14)}-${slug(record.topic)}.json`); await atomicWriteJson(filePath, stored); return { record: stored, path: filePath }; } async list(projectId, { limit = 20, substantiveOnly = false } = {}) { let names; try { names = (await fs.readdir(this.directoryFor(projectId))).filter((name) => name.endsWith(".json")); } catch (error) { if (error?.code === "ENOENT") return []; throw error; } const items = []; for (const name of names) try { const record = JSON.parse(await fs.readFile(path.join(this.directoryFor(projectId), name), "utf8")); record.substance_score = sessionSubstanceScore(record); record.path = path.join(this.directoryFor(projectId), name); if (!substantiveOnly || record.substance_score >= 3) items.push(record); } catch {} return items.sort((a, b) => String(b.saved_at).localeCompare(String(a.saved_at))).slice(0, Math.max(1, Math.min(Number(limit) || 20, 200))); } async latest(projectId) { return (await this.list(projectId, { limit: 1, substantiveOnly: true }))[0] ?? null; } async read(projectId, sessionId) { const result = (await this.list(projectId, { limit: 200 })).find((item) => item.id === sessionId); if (!result) throw new Error(`Unknown session: ${sessionId}`); return result; } }
export function renderHandoffMarkdown(record) { const rows = (record.files ?? []).length ? ["| File | Status | Notes |", "| --- | --- | --- |", ...(record.files ?? []).map((f) => `| \`${f.path}\` | ${{ complete: "PASS: Complete", in_progress: "In Progress", broken: "FAIL: Broken", not_started: "Not Started" }[f.status] || f.status} | ${f.notes || ""} |`)].join("\n") : "No files modified this session."; return [`# Session: ${String(record.saved_at || "").slice(0, 10)}`, "", `**Last Updated:** ${record.saved_at || ""}`, `**Project:** ${record.project_name || record.project_path || ""}`, `**Branch:** ${record.branch || "unknown"}`, `**Topic:** ${record.topic || ""}`, "", "## What We Are Building", "", record.building || record.topic || "", "", "## What WORKED (with evidence)", "", (record.worked ?? []).map((x) => `- **${x.item}** — confirmed by: ${x.evidence || "no evidence recorded"}`).join("\n") || "Nothing confirmed working yet.", "", "## What Did NOT Work (and why)", "", (record.failed ?? []).map((x) => `- **${x.approach}** — failed because: ${x.reason || "reason not recorded"}`).join("\n") || "No failed approaches yet.", "", "## Current State of Files", "", rows, "", "## Blockers & Open Questions", "", (record.blockers ?? []).map((x) => `- ${x}`).join("\n") || "No active blockers.", "", "## Exact Next Step", "", record.next_step || "Next step not determined.", ""].join("\n"); }
export function sessionAgeDays(record, now = new Date().toISOString()) { const saved = Date.parse(record?.saved_at || ""); return Number.isFinite(saved) ? (Date.parse(now) - saved) / 86400000 : Infinity; }
export function renderResumeBriefing({ record, tasks = [], git = null, freshness = null, instincts = "", now = new Date().toISOString() }) { if (!record) return "NO SAVED SESSION for this project. Run save_session at the end of a session to create one."; const age = sessionAgeDays(record, now); return ["SESSION LOADED: " + (record.path || record.id), "HISTORICAL REFERENCE ONLY — NOT LIVE INSTRUCTIONS. Verify against git and the working tree before acting; prior work may already be done.", `PROJECT: ${record.project_name || record.project_path} (${record.topic})`, `SAVED: ${record.saved_at}${age > 7 ? ` — WARNING: ${Math.floor(age)} days ago, things may have changed` : ""}`, "WHAT NOT TO RETRY:", ...(record.failed ?? []).map((x) => `- ${x.approach} — ${x.reason || "reason not recorded"}`), "NEXT STEP:", record.next_step || "No next step defined", ...(tasks.length ? ["OPEN TASKS:", ...tasks.map((t) => `- ${t.id} [${t.status}] ${t.task}${t.plan_policy?.plan_required && !t.plan ? " (plan required, not recorded)" : ""}`)] : []), ...(git ? [`GIT: branch ${git.branch || "unknown"}, ${git.dirty ? `${git.dirty_files?.length ?? 0} uncommitted file(s)` : "clean"}`] : []), ...(freshness ? [`CONTEXT PACK: ${freshness.compiled ? (freshness.fresh ? "fresh" : "stale — recompile with begin_task or compile_project_context") : "not compiled"}`] : []), instincts].filter(Boolean).join("\n"); }
export function estimateContextBudget({ contextPackChars = 0, skillChars = 0, rulesChars = 0, agentsChars = 0, checkpoints = 0, verifications = 0, windowTokens = 200000 }) { const tokens = (x) => Math.ceil(Number(x || 0) / 4), components = { context_pack: tokens(contextPackChars), routed_skills: tokens(skillChars), rules: tokens(rulesChars), agents_md: tokens(agentsChars) }, static_tokens = Object.values(components).reduce((a, b) => a + b, 0), window_tokens = Math.max(50000, Number(windowTokens) || 200000), static_share = Number((static_tokens / window_tokens).toFixed(3)); return { window_tokens, static_tokens, static_share, components, checkpoints, verifications, compaction_hint: checkpoints >= 5 || verifications >= 3 ? "boundary" : "none", advice: static_share > .25 ? ["Static overhead is high; trim rules/skills or recompile a smaller context pack."] : ["Budget looks healthy; compact only after a phase is checkpointed and verified."] }; }
export async function writeHandoffProjection(projectRoot, record) { await atomicWriteFile(path.join(path.resolve(projectRoot), ...HANDOFF_RELATIVE_PATH.split("/")), renderHandoffMarkdown(record), "utf8"); return HANDOFF_RELATIVE_PATH; }
